import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.Color;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Marks.java
 *
 * Created on 16 Nov, 2017, 8:02:36 PM
 */

/**
 *
 * @author HP
 */
public class Marks extends javax.swing.JFrame {

    /** Creates new form Marks */
    public Marks() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ADM NO", "ENGLISH", "MATHS", "HINDI", "HISTORY", "SCIENCE"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButton1.setText("DISPLAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("ADM NO");

        jLabel2.setText("ENGLISH");

        jLabel3.setText("MATHS");

        jLabel4.setText("HINDI");

        jLabel5.setText("HISTORY");

        jLabel6.setText("SCIENCE");

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("RESULT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("MODIFY");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jButton2)))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(80, 80, 80)
                                .addComponent(jButton5)
                                .addGap(38, 38, 38)
                                .addComponent(jButton4)
                                .addGap(74, 74, 74)
                                .addComponent(jButton6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                .addComponent(txt2)
                                .addComponent(txt3)
                                .addComponent(txt4)
                                .addComponent(txt5)
                                .addComponent(txt6)))
                        .addGap(107, 107, 107))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int rows=model.getRowCount();
        if(rows>0)
        { for(int i=0;i<rows;i++)
            { model.removeRow(0);}}
        try{Class.forName("java.sql.DriverManager");
            Connection cn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","bhaggu@99");
            Statement stmt=(Statement)cn.createStatement();
            String query1="Select * from marks;";
            ResultSet rs=stmt.executeQuery(query1);
            while(rs.next())
            { String ad=rs.getString("admno");
                String eng=rs.getString("eng");
                String maths=rs.getString("maths");
                String hindi=rs.getString("hindi");
                String history=rs.getString("history");
                String science=rs.getString("science");
                String t=rs.getString("tot");
                   String p=rs.getString("per");
                   String grade=rs.getString("grade");
                String res=rs.getString("res");
                model.addRow(new Object[]{ad,eng,maths,hindi,history,science});
            }}
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            int rows=model.getRowCount();
        if(rows>0)
        {
            for(int i=0;i<rows;i++)
            {
                model.removeRow(0);
            }
        }
            int rno=0;
        try{
              Class.forName("java.sql.DriverManager");
            Connection cn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","bhaggu@99");
            Statement stmt=(Statement)cn.createStatement();
            int n=Integer.parseInt(txt1.getText());
            try{
                String queryx="SElect * from detail where admno="+n+";";
            ResultSet rs=stmt.executeQuery(queryx);
            while(rs.next())
            {
                rno=Integer.parseInt(rs.getString("rno"));
            }
                if(rno!=0)
                {  int m1=Integer.parseInt(txt2.getText());
                   int m2=Integer.parseInt(txt3.getText());
                   int m3=Integer.parseInt(txt4.getText());
                   int m4=Integer.parseInt(txt5.getText());
                   int m5=Integer.parseInt(txt6.getText());
                   int total=m1+m2+m3+m4+m5;
                   double per=total/5;
                   char ch=' ';
                   String res=" ";
                   if(per>=90)
                   {   ch='O';
                   res="PASS";}
                  if((per<90)&&(per>=80))
                  { ch='A';
                       res="PASS";}
                   if((per<80)&&(per>=70))
                   {   ch='B';
                       res="PASS";}
                   if((per<70)&&(per>=60))
                   {   ch='C';
                       res="PASS";}
                   if((per<60)&&(per>=50))
                   {  ch='D';
                       res="PASS";}
                   if(per<50&&(per>=35))
                   { ch='E';
                       res="PASS";}
                       if(per<35)
                       { ch='F';
                       res="FAIL";
                       }
                    String query="insert into marks values("+n+","+m1+","+m2+","+m3+","+m4+","+m5+","+total+"," +
                            ""+per+",'"+ch+"','"+res+"');";
                  stmt.executeUpdate(query);
                }
                else
                { JOptionPane.showMessageDialog(null,"Student Details not present");}
            }
            catch(Exception e)
            {JOptionPane.showMessageDialog(null,e.getMessage());}
            txt1.setText("");
            txt2.setText("");
            txt3.setText("");
            txt4.setText("");
            txt5.setText("");
            txt6.setText("");
            String query1="Select * from marks;";
            ResultSet rs=stmt.executeQuery(query1);
            while(rs.next())
            {   String ad=rs.getString("admno");
                String eng=rs.getString("eng");
                String maths=rs.getString("maths");
                String hindi=rs.getString("hindi");
                String history=rs.getString("history");
                String science=rs.getString("science");
                String t=rs.getString("tot");
                   String p=rs.getString("per");
                   String grade=rs.getString("grade");
                String res=rs.getString("res");
                model.addRow(new Object[]{ad,eng,maths,hindi,history,science});}}
        catch(Exception e)
        {JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      int admno=Integer.parseInt(JOptionPane.showInputDialog("Enter the admno of the record to be deleted..."));
        try{
            Class.forName("java.sql.DriverManager");
            Connection cn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","bhaggu@99");
            Statement stmt=(Statement)cn.createStatement();
            ResultSet rs;
            int opt=JOptionPane.showConfirmDialog(null,"confirm Deletion?");
            if(opt==JOptionPane.YES_OPTION)
            {
                try{
                    String strSQL="DElete from marks where admno="+admno+";";
                    int rowsEffected=stmt.executeUpdate(strSQL);
                    if(rowsEffected==0)
                    {
                        JOptionPane.showMessageDialog(this,"Record does not exist");
                    }
                        else
                        {
                            JOptionPane.showMessageDialog(this,"Record Deleted");
                        }
                    }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"unable to delete");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Operation Cancelled");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showConfirmDialog(null,e.getMessage());
        }
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int rows=model.getRowCount();
        if(rows>0)
        {
            for(int i=0;i<rows;i++)
            {
                model.removeRow(0);
            }
        }
        try{
              Class.forName("java.sql.DriverManager");
            Connection cn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
            Statement stmt=(Statement)cn.createStatement();
           String query1="Select * from marks;";
            ResultSet rs=stmt.executeQuery(query1);
            while(rs.next())
            {
                String ad=rs.getString("admno");
                String eng=rs.getString("eng");
                String maths=rs.getString("maths");
                String hindi=rs.getString("hindi");
                String history=rs.getString("history");
                String science=rs.getString("science");
                model.addRow(new Object[]{ad,eng,maths,hindi,history,science});
            }
            }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new A().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new mod2().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new aLogin().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    // End of variables declaration//GEN-END:variables

}
