import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mod2.java
 *
 * Created on 21 Nov, 2017, 7:19:38 PM
 */

/**
 *
 * @author HP
 */
public class mod2 extends javax.swing.JFrame {

    /** Creates new form mod2 */
    public mod2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ADM NO");

        jLabel2.setText("ENGLISH");

        jLabel3.setText("MATHS");

        jLabel4.setText("HINDI");

        jLabel5.setText("HISTORY");

        jLabel6.setText("SCIENCE");

        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });

        jCheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox2MouseClicked(evt);
            }
        });

        jCheckBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox3MouseClicked(evt);
            }
        });

        jCheckBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox4MouseClicked(evt);
            }
        });

        jCheckBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox5MouseClicked(evt);
            }
        });

        jButton1.setText("MODIFY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("DISPLAY MODIFIED TEXT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jButton1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBox4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBox2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBox3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBox1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))
                        .addContainerGap(54, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox2)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox4)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox5)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
   int ad=Integer.parseInt(jTextField1.getText());
       String query="";
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection cn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","bhaggu@99");
            Statement stmt=(Statement)cn.createStatement();
           int a1,a2,a3,a4,a5,total;double per;char ch;String res;
            String query1="SElect * from marks where admno="+ad+";";
            ResultSet rs=stmt.executeQuery(query1);
            if(rs.next())
            {
                String adm=rs.getString("admno");
                String e=rs.getString("eng");
                String m=rs.getString("maths");
                String h=rs.getString("hindi");
                String h1=rs.getString("history");
                String s=rs.getString("science");
                int eng=Integer.parseInt(e);
                int mat=Integer.parseInt(m);
                int hin=Integer.parseInt(h);
                int his=Integer.parseInt(h1);
                int sci=Integer.parseInt(s);
            ResultSet rs1 = null;
            if(jCheckBox1.isSelected())
            {   a1=Integer.parseInt(jTextField2.getText());
                 total=a1+mat+hin+his+sci;
                   per=total/5;
                   ch=' ';
                  res=" ";
                   if(per>=90)
                   {   ch='O';
                   res="PASS";}
                  if((per<90)&&(per>=80))
                  { ch='A';
                       res="PASS";}
                   if((per<80)&&(per>=70))
                   {   ch='B';
                       res="PASS";}
                   if((per<70)&&(per>=60))
                   {   ch='C';
                       res="PASS";}
                   if((per<60)&&(per>=50))
                   {  ch='D';
                       res="PASS";}
                   if(per<50&&(per>=35))
                   { ch='E';
                       res="PASS";}
                       if(per<35)
                       { ch='F';
                       res="FAIL";
                       }
                query="update marks set admno="+ad+",eng="+a1+",maths="+mat+",hindi="+hin+",history="+his+",science="+sci+",tot="+total+",per="+per+",grade='"+ch+"',res='"+res+"' where admno="+(ad)+";";
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(this,"REcord modified");
                 jTextField1.setText("");
                  jTextField2.setText("");
            jTextField2.setEnabled(true);
            jTextField3.setEnabled(true);
             jTextField4.setEnabled(true);
            jTextField5.setEnabled(true);
            jTextField6.setEnabled(true);
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
            jCheckBox4.setSelected(false);
            jCheckBox1.setSelected(false);
            jCheckBox5.setSelected(false);
            jCheckBox2.setEnabled(true);
            jCheckBox3.setEnabled(true);
            jCheckBox4.setEnabled(true);
            jCheckBox1.setEnabled(true);
            jCheckBox5.setEnabled(true);
            }
             if(jCheckBox2.isSelected())
            {     a2=Integer.parseInt(jTextField3.getText());
                  total=eng+a2+hin+his+sci;
                   per=total/5;
                   ch=' ';
                   res=" ";
                   if(per>=90)
                   {   ch='O';
                   res="PASS";}
                  if((per<90)&&(per>=80))
                  { ch='A';
                       res="PASS";}
                   if((per<80)&&(per>=70))
                   {   ch='B';
                       res="PASS";}
                   if((per<70)&&(per>=60))
                   {   ch='C';
                       res="PASS";}
                   if((per<60)&&(per>=50))
                   {  ch='D';
                       res="PASS";}
                   if(per<50&&(per>=35))
                   { ch='E';
                       res="PASS";}
                       if(per<35)
                       { ch='F';
                       res="FAIL";
                       }
                query="update marks set admno="+ad+",eng="+eng+",maths="+a2+",hindi="+hin+",history="+his+",science="+sci+",tot="+total+",per="+per+",grade='"+ch+"',res='"+res+"' where admno="+(ad)+";";
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(this,"REcord modified");
                 jTextField1.setText("");
                  jTextField2.setText("");
            jTextField2.setEnabled(true);
            jTextField3.setEnabled(true);
             jTextField4.setEnabled(true);
            jTextField5.setEnabled(true);
            jTextField6.setEnabled(true);
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
            jCheckBox4.setSelected(false);
            jCheckBox1.setSelected(false);
            jCheckBox5.setSelected(false);
            jCheckBox2.setEnabled(true);
            jCheckBox3.setEnabled(true);
            jCheckBox4.setEnabled(true);
            jCheckBox1.setEnabled(true);
            jCheckBox5.setEnabled(true);
               if(jCheckBox3.isSelected())
            {     a3=Integer.parseInt(jTextField4.getText());
                  total=eng+mat+a3+his+sci;
                   per=total/5;
                   ch=' ';
                   res=" ";
                   if(per>=90)
                   {   ch='O';
                   res="PASS";}
                  if((per<90)&&(per>=80))
                  { ch='A';
                       res="PASS";}
                   if((per<80)&&(per>=70))
                   {   ch='B';
                       res="PASS";}
                   if((per<70)&&(per>=60))
                   {   ch='C';
                       res="PASS";}
                   if((per<60)&&(per>=50))
                   {  ch='D';
                       res="PASS";}
                   if(per<50&&(per>=35))
                   { ch='E';
                       res="PASS";}
                       if(per<35)
                       { ch='F';
                       res="FAIL";
                       }
                query="update marks set admno="+ad+",eng="+eng+",maths="+mat+",hindi="+a3+",history="+his+",science="+sci+",tot="+total+",per="+per+",grade='"+ch+"',res='"+res+"' where admno="+(ad)+";";
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(this,"REcord modified");
                 jTextField1.setText("");
                  jTextField2.setText("");
            jTextField2.setEnabled(true);
            jTextField3.setEnabled(true);
             jTextField4.setEnabled(true);
            jTextField5.setEnabled(true);
            jTextField6.setEnabled(true);
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
            jCheckBox4.setSelected(false);
            jCheckBox1.setSelected(false);
            jCheckBox5.setSelected(false);
            jCheckBox2.setEnabled(true);
            jCheckBox3.setEnabled(true);
            jCheckBox4.setEnabled(true);
            jCheckBox1.setEnabled(true);
            jCheckBox5.setEnabled(true);
            }
              if(jCheckBox4.isSelected())
            {    a4=Integer.parseInt(jTextField5.getText());
                 total=eng+mat+hin+a4+sci;
                   per=total/5;
                   ch=' ';
                   res=" ";
                   if(per>=90)
                   {   ch='O';
                   res="PASS";}
                  if((per<90)&&(per>=80))
                  { ch='A';
                       res="PASS";}
                   if((per<80)&&(per>=70))
                   {   ch='B';
                       res="PASS";}
                   if((per<70)&&(per>=60))
                   {   ch='C';
                       res="PASS";}
                   if((per<60)&&(per>=50))
                   {  ch='D';
                       res="PASS";}
                   if(per<50&&(per>=35))
                   { ch='E';
                       res="PASS";}
                       if(per<35)
                       { ch='F';
                       res="FAIL";
                       }
                query="update marks set admno="+ad+",eng="+eng+",maths="+mat+",hindi="+hin+",history="+a4+",science="+sci+",tot="+total+",per="+per+",grade='"+ch+"',res='"+res+"' where admno="+(ad)+";";
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(this,"REcord modified");
                 jTextField1.setText("");
                  jTextField2.setText("");
            jTextField2.setEnabled(true);
            jTextField3.setEnabled(true);
             jTextField4.setEnabled(true);
            jTextField5.setEnabled(true);
            jTextField6.setEnabled(true);
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
            jCheckBox4.setSelected(false);
            jCheckBox1.setSelected(false);
            jCheckBox5.setSelected(false);
            jCheckBox2.setEnabled(true);
            jCheckBox3.setEnabled(true);
            jCheckBox4.setEnabled(true);
            jCheckBox1.setEnabled(true);
            jCheckBox5.setEnabled(true);
            }
             if(jCheckBox5.isSelected())
            {    a5=Integer.parseInt(jTextField6.getText());
                 total=eng+mat+hin+his+a5;
                   per=total/5;
                   ch=' ';
                  res=" ";
                   if(per>=90)
                   {   ch='O';
                   res="PASS";}
                  if((per<90)&&(per>=80))
                  { ch='A';
                       res="PASS";}
                   if((per<80)&&(per>=70))
                   {   ch='B';
                       res="PASS";}
                   if((per<70)&&(per>=60))
                   {   ch='C';
                       res="PASS";}
                   if((per<60)&&(per>=50))
                   {  ch='D';
                       res="PASS";}
                   if(per<50&&(per>=35))
                   { ch='E';
                       res="PASS";}
                       if(per<35)
                       { ch='F';
                       res="FAIL";
                       }
                query="update marks set admno="+ad+",eng="+eng+",maths="+mat+",hindi="+hin+",history="+his+",science="+a5+",tot="+total+",per="+per+",grade='"+ch+"',res='"+res+"' where admno="+(ad)+";";
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(this,"REcord modified");
                 jTextField1.setText("");
                  jTextField2.setText("");
            jTextField2.setEnabled(true);
            jTextField3.setEnabled(true);
             jTextField4.setEnabled(true);
            jTextField5.setEnabled(true);
            jTextField6.setEnabled(true);
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
            jCheckBox4.setSelected(false);
            jCheckBox1.setSelected(false);
            jCheckBox5.setSelected(false);
            jCheckBox2.setEnabled(true);
            jCheckBox3.setEnabled(true);
            jCheckBox4.setEnabled(true);
            jCheckBox1.setEnabled(true);
            jCheckBox5.setEnabled(true);
            }
             }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showConfirmDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        // TODO add your handling code here:
            jTextField3.setEnabled(false);
            jTextField4.setEnabled(false);
            jTextField5.setEnabled(false);
            jTextField6.setEnabled(false);
            jCheckBox2.setEnabled(false);
            jCheckBox3.setEnabled(false);
            jCheckBox4.setEnabled(false);
            jCheckBox5.setEnabled(false);
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void jCheckBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox2MouseClicked
        // TODO add your handling code here:
            jTextField2.setEnabled(false);
            jTextField4.setEnabled(false);
            jTextField5.setEnabled(false);
            jTextField6.setEnabled(false);
            jCheckBox1.setEnabled(false);
            jCheckBox3.setEnabled(false);
            jCheckBox4.setEnabled(false);
            jCheckBox5.setEnabled(false);
    }//GEN-LAST:event_jCheckBox2MouseClicked

    private void jCheckBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox3MouseClicked
        // TODO add your handling code here:
         jTextField3.setEnabled(false);
            jTextField2.setEnabled(false);
            jTextField5.setEnabled(false);
            jTextField6.setEnabled(false);
            jCheckBox1.setEnabled(false);
            jCheckBox2.setEnabled(false);
            jCheckBox4.setEnabled(false);
            jCheckBox5.setEnabled(false);
    }//GEN-LAST:event_jCheckBox3MouseClicked

    private void jCheckBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox4MouseClicked
        // TODO add your handling code here:
         jTextField3.setEnabled(false);
            jTextField4.setEnabled(false);
            jTextField2.setEnabled(false);
            jTextField6.setEnabled(false);
            jCheckBox2.setEnabled(false);
            jCheckBox3.setEnabled(false);
            jCheckBox1.setEnabled(false);
            jCheckBox5.setEnabled(false);
    }//GEN-LAST:event_jCheckBox4MouseClicked

    private void jCheckBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox5MouseClicked
        // TODO add your handling code here:
         jTextField3.setEnabled(false);
            jTextField4.setEnabled(false);
            jTextField5.setEnabled(false);
            jTextField2.setEnabled(false);
            jCheckBox2.setEnabled(false);
            jCheckBox3.setEnabled(false);
            jCheckBox4.setEnabled(false);
            jCheckBox1.setEnabled(false);
    }//GEN-LAST:event_jCheckBox5MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Mod_marks().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Marks().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mod2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

}
